-- SPX optimizer governance: persisted nightly runtime status + scan/revert audit history

ALTER TABLE IF EXISTS spx_setup_optimizer_state
  ADD COLUMN IF NOT EXISTS last_nightly_run_date_et DATE,
  ADD COLUMN IF NOT EXISTS last_nightly_attempt_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_nightly_success_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_nightly_error_message TEXT;

CREATE TABLE IF NOT EXISTS spx_setup_optimizer_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL CHECK (action IN ('scan', 'revert')),
  mode TEXT NOT NULL CHECK (mode IN ('manual', 'weekly_auto', 'nightly_auto', 'revert')),
  actor TEXT,
  reason TEXT,
  optimization_applied BOOLEAN NOT NULL DEFAULT false,
  previous_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  next_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  scorecard JSONB NOT NULL DEFAULT '{}'::jsonb,
  scan_range_from DATE,
  scan_range_to DATE,
  training_from DATE,
  training_to DATE,
  validation_from DATE,
  validation_to DATE,
  reverted_from_history_id BIGINT REFERENCES spx_setup_optimizer_history(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_spx_optimizer_history_created
  ON spx_setup_optimizer_history(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_spx_optimizer_history_action_mode
  ON spx_setup_optimizer_history(action, mode, created_at DESC);

ALTER TABLE spx_setup_optimizer_history ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'spx_setup_optimizer_history'
      AND policyname = 'select_spx_setup_optimizer_history'
  ) THEN
    CREATE POLICY select_spx_setup_optimizer_history
      ON spx_setup_optimizer_history
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END
$$;
