-- Auto-generated by scripts/academy-v3/generate-seed-sql.mjs
-- Source blueprint: docs/specs/academy-content/foundations-program.seed.json
BEGIN;

-- Program
INSERT INTO academy_programs (code, title, description, is_active, metadata)
VALUES ('titm-core-program', 'TITM Trader Development Program', 'Competency-based program for options execution, risk, and review discipline', true, '{}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Track: foundations
INSERT INTO academy_tracks (program_id, code, title, description, position, is_active, metadata)
VALUES (
  (SELECT id FROM academy_programs WHERE code = 'titm-core-program'),
  'foundations',
  'Foundations',
  '',
  1,
  true,
  '{}'::jsonb
)
ON CONFLICT (program_id, code) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  position = EXCLUDED.position,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Module: market-context-core
INSERT INTO academy_modules (track_id, slug, code, title, description, learning_outcomes, estimated_minutes, position, is_published, metadata)
VALUES (
  (SELECT t.id FROM academy_tracks t JOIN academy_programs p ON p.id = t.program_id WHERE p.code = 'titm-core-program' AND t.code = 'foundations'),
  'market-context-core',
  'market-context-core',
  'Market Context Fundamentals',
  'Learn to identify session context before entering risk.',
  '["Classify trend, range, and transition sessions","Define invalidation zones before entry","Select setups aligned to session context"]'::jsonb,
  70,
  1,
  true,
  '{}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  learning_outcomes = EXCLUDED.learning_outcomes,
  estimated_minutes = EXCLUDED.estimated_minutes,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  updated_at = now();

-- Lesson: session-framing-for-options
INSERT INTO academy_lessons (module_id, slug, title, learning_objective, estimated_minutes, difficulty, prerequisite_lesson_ids, position, is_published, metadata)
VALUES (
  (SELECT id FROM academy_modules WHERE slug = 'market-context-core'),
  'session-framing-for-options',
  'Session Framing for Options',
  'Build a repeatable pre-trade context checklist before opening a position.',
  18,
  'beginner'::academy_difficulty,
  '{}'::uuid[],
  1,
  true,
  '{"competenciesTargeted":["market_context","entry_validation"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  learning_objective = EXCLUDED.learning_objective,
  estimated_minutes = EXCLUDED.estimated_minutes,
  difficulty = EXCLUDED.difficulty,
  prerequisite_lesson_ids = EXCLUDED.prerequisite_lesson_ids,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Block 1: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'hook'::academy_block_type,
  1,
  'Why Context Beats Conviction',
  '{"title":"Why Context Beats Conviction","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Start with a concrete market moment and identify why it mattered."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 2: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'concept_explanation'::academy_block_type,
  2,
  'Three Session Modes',
  '{"title":"Three Session Modes","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Explain the concept with one actionable decision rule."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 3: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'worked_example'::academy_block_type,
  3,
  'SPX Open: Range to Trend Transition',
  '{"title":"SPX Open: Range to Trend Transition","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Walk through a realistic setup from context to decision."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 4: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'guided_practice'::academy_block_type,
  4,
  'Tag Context From a Chart Snapshot',
  '{"title":"Tag Context From a Chart Snapshot","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Complete the guided prompt and compare your reasoning."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 5: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'independent_practice'::academy_block_type,
  5,
  'Write Your 5-Point Context Plan',
  '{"title":"Write Your 5-Point Context Plan","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Solve the scenario independently before checking feedback."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 6: session-framing-for-options
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  'reflection'::academy_block_type,
  6,
  'What Invalidates Your Bias Fastest?',
  '{"title":"What Invalidates Your Bias Fastest?","lessonTitle":"Session Framing for Options","lessonObjective":"Build a repeatable pre-trade context checklist before opening a position.","instruction":"Write what you would change next session and why."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Lesson: invalidations-and-levels
INSERT INTO academy_lessons (module_id, slug, title, learning_objective, estimated_minutes, difficulty, prerequisite_lesson_ids, position, is_published, metadata)
VALUES (
  (SELECT id FROM academy_modules WHERE slug = 'market-context-core'),
  'invalidations-and-levels',
  'Invalidations and Key Levels',
  'Mark invalidation and target levels that define whether a trade remains valid.',
  16,
  'beginner'::academy_difficulty,
  '{}'::uuid[],
  2,
  true,
  '{"competenciesTargeted":["market_context","trade_management"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  learning_objective = EXCLUDED.learning_objective,
  estimated_minutes = EXCLUDED.estimated_minutes,
  difficulty = EXCLUDED.difficulty,
  prerequisite_lesson_ids = EXCLUDED.prerequisite_lesson_ids,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Block 1: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'hook'::academy_block_type,
  1,
  'The Cost of Unclear Invalidations',
  '{"title":"The Cost of Unclear Invalidations","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Start with a concrete market moment and identify why it mattered."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 2: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'concept_explanation'::academy_block_type,
  2,
  'Level Hierarchy and Timeframe Priority',
  '{"title":"Level Hierarchy and Timeframe Priority","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Explain the concept with one actionable decision rule."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 3: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'worked_example'::academy_block_type,
  3,
  'Morning Breakdown Recovery Scenario',
  '{"title":"Morning Breakdown Recovery Scenario","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Walk through a realistic setup from context to decision."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 4: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'guided_practice'::academy_block_type,
  4,
  'Place Invalidation and First Target',
  '{"title":"Place Invalidation and First Target","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Complete the guided prompt and compare your reasoning."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 5: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'independent_practice'::academy_block_type,
  5,
  'Annotate Two Alternate Scenarios',
  '{"title":"Annotate Two Alternate Scenarios","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Solve the scenario independently before checking feedback."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 6: invalidations-and-levels
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  'reflection'::academy_block_type,
  6,
  'How Early Should You Exit?',
  '{"title":"How Early Should You Exit?","lessonTitle":"Invalidations and Key Levels","lessonObjective":"Mark invalidation and target levels that define whether a trade remains valid.","instruction":"Write what you would change next session and why."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Module summative assessment: market-context-core
INSERT INTO academy_assessments (module_id, title, assessment_type, mastery_threshold, is_published, metadata)
SELECT
  m.id, 'Market Context Fundamentals Mastery Check', 'summative'::academy_assessment_type, 0.75, true, '{}'::jsonb
FROM academy_modules m
WHERE m.slug = 'market-context-core'
  AND NOT EXISTS (
    SELECT 1 FROM academy_assessments a
    WHERE a.module_id = m.id
      AND a.title = 'Market Context Fundamentals Mastery Check'
      AND a.assessment_type = 'summative'::academy_assessment_type
  );

-- Module: risk-and-execution-core
INSERT INTO academy_modules (track_id, slug, code, title, description, learning_outcomes, estimated_minutes, position, is_published, metadata)
VALUES (
  (SELECT t.id FROM academy_tracks t JOIN academy_programs p ON p.id = t.program_id WHERE p.code = 'titm-core-program' AND t.code = 'foundations'),
  'risk-and-execution-core',
  'risk-and-execution-core',
  'Risk and Execution Discipline',
  'Translate setup quality into size, management, and disciplined exits.',
  '["Size positions by invalidation distance and account risk","Plan scale-out and hard-stop behavior before entry","Use post-trade reflection to reduce repeat mistakes"]'::jsonb,
  80,
  2,
  true,
  '{}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  learning_outcomes = EXCLUDED.learning_outcomes,
  estimated_minutes = EXCLUDED.estimated_minutes,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  updated_at = now();

-- Lesson: sizing-with-invalidation
INSERT INTO academy_lessons (module_id, slug, title, learning_objective, estimated_minutes, difficulty, prerequisite_lesson_ids, position, is_published, metadata)
VALUES (
  (SELECT id FROM academy_modules WHERE slug = 'risk-and-execution-core'),
  'sizing-with-invalidation',
  'Position Sizing With Invalidation',
  'Compute position size from account risk and invalidation distance.',
  20,
  'intermediate'::academy_difficulty,
  '{}'::uuid[],
  1,
  true,
  '{"competenciesTargeted":["position_sizing","entry_validation"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  learning_objective = EXCLUDED.learning_objective,
  estimated_minutes = EXCLUDED.estimated_minutes,
  difficulty = EXCLUDED.difficulty,
  prerequisite_lesson_ids = EXCLUDED.prerequisite_lesson_ids,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Block 1: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'hook'::academy_block_type,
  1,
  'Why Good Setups Still Blow Up Accounts',
  '{"title":"Why Good Setups Still Blow Up Accounts","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Start with a concrete market moment and identify why it mattered."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 2: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'concept_explanation'::academy_block_type,
  2,
  'Risk Budget and Size Formula',
  '{"title":"Risk Budget and Size Formula","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Explain the concept with one actionable decision rule."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 3: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'worked_example'::academy_block_type,
  3,
  'Sizing Two Contracts Across Volatility Regimes',
  '{"title":"Sizing Two Contracts Across Volatility Regimes","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Walk through a realistic setup from context to decision."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 4: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'guided_practice'::academy_block_type,
  4,
  'Size the Trade in Three Scenarios',
  '{"title":"Size the Trade in Three Scenarios","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Complete the guided prompt and compare your reasoning."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 5: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'independent_practice'::academy_block_type,
  5,
  'Build Your Personal Size Table',
  '{"title":"Build Your Personal Size Table","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Solve the scenario independently before checking feedback."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 6: sizing-with-invalidation
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  'reflection'::academy_block_type,
  6,
  'When to Reduce Size Despite Strong Conviction',
  '{"title":"When to Reduce Size Despite Strong Conviction","lessonTitle":"Position Sizing With Invalidation","lessonObjective":"Compute position size from account risk and invalidation distance.","instruction":"Write what you would change next session and why."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Lesson: exit-discipline-under-pressure
INSERT INTO academy_lessons (module_id, slug, title, learning_objective, estimated_minutes, difficulty, prerequisite_lesson_ids, position, is_published, metadata)
VALUES (
  (SELECT id FROM academy_modules WHERE slug = 'risk-and-execution-core'),
  'exit-discipline-under-pressure',
  'Exit Discipline Under Pressure',
  'Execute pre-defined exits consistently when trades move quickly.',
  19,
  'intermediate'::academy_difficulty,
  '{}'::uuid[],
  2,
  true,
  '{"competenciesTargeted":["exit_discipline","review_reflection"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  learning_objective = EXCLUDED.learning_objective,
  estimated_minutes = EXCLUDED.estimated_minutes,
  difficulty = EXCLUDED.difficulty,
  prerequisite_lesson_ids = EXCLUDED.prerequisite_lesson_ids,
  position = EXCLUDED.position,
  is_published = EXCLUDED.is_published,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Block 1: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'hook'::academy_block_type,
  1,
  'Most PnL Damage Happens After Entry',
  '{"title":"Most PnL Damage Happens After Entry","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Start with a concrete market moment and identify why it mattered."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 2: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'concept_explanation'::academy_block_type,
  2,
  'Three Exit Triggers You Must Define',
  '{"title":"Three Exit Triggers You Must Define","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Explain the concept with one actionable decision rule."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 3: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'worked_example'::academy_block_type,
  3,
  'Fast Reversal: Stick to Plan or Hope',
  '{"title":"Fast Reversal: Stick to Plan or Hope","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Walk through a realistic setup from context to decision."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 4: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'guided_practice'::academy_block_type,
  4,
  'Choose Exits for Four Replay Segments',
  '{"title":"Choose Exits for Four Replay Segments","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Complete the guided prompt and compare your reasoning."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 5: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'independent_practice'::academy_block_type,
  5,
  'Write an Exit Decision Tree',
  '{"title":"Write an Exit Decision Tree","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Solve the scenario independently before checking feedback."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Block 6: exit-discipline-under-pressure
INSERT INTO academy_lesson_blocks (lesson_id, block_type, position, title, content_json)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  'reflection'::academy_block_type,
  6,
  'Which Bias Broke Your Last Exit?',
  '{"title":"Which Bias Broke Your Last Exit?","lessonTitle":"Exit Discipline Under Pressure","lessonObjective":"Execute pre-defined exits consistently when trades move quickly.","instruction":"Write what you would change next session and why."}'::jsonb
)
ON CONFLICT (lesson_id, position) DO UPDATE SET
  block_type = EXCLUDED.block_type,
  title = EXCLUDED.title,
  content_json = EXCLUDED.content_json,
  updated_at = now();

-- Module summative assessment: risk-and-execution-core
INSERT INTO academy_assessments (module_id, title, assessment_type, mastery_threshold, is_published, metadata)
SELECT
  m.id, 'Risk and Execution Discipline Mastery Check', 'summative'::academy_assessment_type, 0.75, true, '{}'::jsonb
FROM academy_modules m
WHERE m.slug = 'risk-and-execution-core'
  AND NOT EXISTS (
    SELECT 1 FROM academy_assessments a
    WHERE a.module_id = m.id
      AND a.title = 'Risk and Execution Discipline Mastery Check'
      AND a.assessment_type = 'summative'::academy_assessment_type
  );

-- Competencies
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('entry_validation', 'Entry Validation', 'Confirm setup quality and invalidation before execution.', 'execution', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('exit_discipline', 'Exit Discipline', 'Execute planned exits under pressure without drift.', 'risk', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('market_context', 'Market Context', 'Evaluate session structure and context before taking risk.', 'analysis', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('position_sizing', 'Position Sizing', 'Size trades from defined risk and invalidation distance.', 'risk', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('review_reflection', 'Review Reflection', 'Use post-trade review to improve repeatability.', 'improvement', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();
INSERT INTO academy_competencies (key, title, description, domain, metadata)
VALUES ('trade_management', 'Trade Management', 'Manage live positions with predefined adaptation rules.', 'execution', '{}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  updated_at = now();

INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  (SELECT id FROM academy_competencies WHERE key = 'market_context'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'session-framing-for-options'),
  (SELECT id FROM academy_competencies WHERE key = 'entry_validation'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  (SELECT id FROM academy_competencies WHERE key = 'market_context'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'invalidations-and-levels'),
  (SELECT id FROM academy_competencies WHERE key = 'trade_management'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  (SELECT id FROM academy_competencies WHERE key = 'position_sizing'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'sizing-with-invalidation'),
  (SELECT id FROM academy_competencies WHERE key = 'entry_validation'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  (SELECT id FROM academy_competencies WHERE key = 'exit_discipline'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;
INSERT INTO academy_lesson_competencies (lesson_id, competency_id, weight)
VALUES (
  (SELECT id FROM academy_lessons WHERE slug = 'exit-discipline-under-pressure'),
  (SELECT id FROM academy_competencies WHERE key = 'review_reflection'),
  1
)
ON CONFLICT (lesson_id, competency_id) DO UPDATE SET
  weight = EXCLUDED.weight;

COMMIT;
